# Generated by Django 2.2 on 2022-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название')),
                ('code', models.CharField(max_length=10, verbose_name='артикул')),
                ('price', models.CharField(max_length=10, verbose_name='цена')),
            ],
        ),
    ]
