# Generated by Django 2.2 on 2022-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='autor',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='autor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='personal_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='autor',
            name='second_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='autor',
            name='univercity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
